#
#   MASTER BRANCH
#
# build in Release mode

- branches:
    only:
    - master

  skip_tags: true
  configuration: Release
  platform: Any CPU

  environment:
    use_build_number_in_packages: true

  artifacts:
    - path: src\build\Release
    - path: src\build\nuget\*.nupkg
    - path: "templates\Radical Templates\bin\Release\*.vsix"

  cache:
    - src\packages -> src\**\packages.config

  before_build:
    - nuget restore "Radical VisualStudio Templates.sln"

  build:
    project: "Radical VisualStudio Templates.sln"
    verbosity: minimal

#  after_build:
#    - md "src\build\nuget"
#    - nuget pack "src\nuget\Radical.nuspec" -Version "%GitVersion_NuGetVersion%" -Properties "configuration=%CONFIGURATION%" -OutputDirectory "src\build\nuget"

  pull_requests:
    do_not_increment_build_number: true

  deploy:
#  - provider: Environment
#    name: NuGet public feed
#    on:
#      branch: master

#  - provider: GitHub    
#    release: $(GitVersion_NuGetVersion)
#    description: 'Release v$(GitVersion_NuGetVersion)'
#    auth_token:
#      secure: 2ijF4OfPYfIUTunubL/Z04ogADL9sx/gKW1jMRNJnAa1OpHZpSvCKmP0gvNs8C7h
#    artifact: /.*\.nupkg/, src\build\Release.zip
#    on:
#      branch: master